GET http://localhost:3003/api/blogs/

###
POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJvdCIsImlkIjoiNjg1MmVjMDJhNGEyMzhmYWMxZjVjM2NkIiwiaWF0IjoxNzUwMjY0ODQxfQ.YAf0O3ngvV4NSCiNCz6DZ3W8LV5BGWO21dXATpxVqao

{
  "title": "You’re NOT gonna need it!",
  "author": "Ron Jeffries",
  "url": "https://ronjeffries.com/xprog/articles/practices/pracnotneed/",
  "likes": 2
}

# {
#   "title": "React patterns",
#   "author": "Michael Chan",
#   "url": "https://reactpatterns.com",
#   "likes": 3
# }

# {
#   "title": "AI is Creating a Generation of Illiterate Programmers",
#   "author": "Neo",
#   "url": "https://nmn.gl/blog/ai-illiterate-programmers",
#   "likes": 7
# }

# {
#   "title": "AI is Creating a Generation of Illiterate Programmers",
#   "author": "Neo",
#   "url": "https://nmn.gl/blog/ai-illiterate-programmers",
#   "likes": 7
# }

# {
#   "title": "Microservices and the First Law of Distributed Objects",
#   "author": "Martin Fowler",
#   "url": "https://martinfowler.com/articles/distributed-objects-microservices.html",
#   "likes": 1,
# }

###
# {
#   "title": "Go To Statement Considered Harmful",
#   "author": "Edsger W. Dijkstra",
#   "url": "http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html",
#   "likes": 5,
# },

###
PUT http://localhost:3003/api/blogs/68603fa14a95725d987558de/upvote
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJvdCIsImlkIjoiNjg1MmVjMDJhNGEyMzhmYWMxZjVjM2NkIiwiaWF0IjoxNzUwMjY0ODQxfQ.YAf0O3ngvV4NSCiNCz6DZ3W8LV5BGWO21dXATpxVqao

###
DELETE http://localhost:3003/api/blogs/6852ec2ca4a238fac1f5c3d2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJvdCIsImlkIjoiNjg1MmVjMDJhNGEyMzhmYWMxZjVjM2NkIiwiaWF0IjoxNzUwMjY0ODQxfQ.YAf0O3ngvV4NSCiNCz6DZ3W8LV5BGWO21dXATpxVqao

### Register User ##############################################################
GET http://localhost:3003/api/users/

### 
POST http://localhost:3003/api/users/
Content-Type: application/json

{
  "name": "Sayanta",
  "username": "bot",
  "password": "idkthepswd"
}

###
DELETE http://localhost:3003/api/users/684b39c1c22a7aab4f91157f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJvdCIsImlkIjoiNjg1MmVjMDJhNGEyMzhmYWMxZjVjM2NkIiwiaWF0IjoxNzUwMjY0ODQxfQ.YAf0O3ngvV4NSCiNCz6DZ3W8LV5BGWO21dXATpxVqao

### Login ######################################################################
POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "bot",
  "password": "idkthepswd"
}